version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app/flask_app
      - ./flask_app/temp_outputs:/app/flask_app/temp_outputs
    env_file:
      - .env
    environment:
      - FLASK_APP=flask_app/app.py
      - FLASK_ENV=production
    restart: unless-stopped

  # Add database service if needed
  # db:
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=digitalclone
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
