version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digitalclone
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - uploads_data:/app/app/static/uploads
    depends_on:
      - redis
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/digitalclone
      - REDIS_URL=redis://redis:6379/0
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-default_dev_secret_key}
    restart: always

volumes:
  postgres_data:
  redis_data:
  uploads_data:
