name: Deploy to Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

jobs:
  deploy-aws:
    if: github.event.inputs.environment == 'production' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Install EB CLI
      run: |
        pip install awsebcli
    
    - name: Create .env file
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "PLAYHT_USERID=${{ secrets.PLAYHT_USERID }}" >> .env
        echo "PLAYHT_SECRET=${{ secrets.PLAYHT_SECRET }}" >> .env
        echo "HUGGING=${{ secrets.HUGGING }}" >> .env
        echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> .env
        echo "GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" >> .env
        echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
    
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p docker digitalclone-iitg --region us-east-1
        eb deploy digitalclone-production || eb create digitalclone-production

  deploy-gcp:
    if: github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io
    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/digitalclone-iitg:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/digitalclone-iitg:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy digitalclone-iitg \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/digitalclone-iitg:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --update-env-vars="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          --update-env-vars="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --update-env-vars="PLAYHT_USERID=${{ secrets.PLAYHT_USERID }}" \
          --update-env-vars="PLAYHT_SECRET=${{ secrets.PLAYHT_SECRET }}" \
          --update-env-vars="HUGGING=${{ secrets.HUGGING }}" \
          --update-env-vars="FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}"
